spring.application.name=blog

# Configuração da DB (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/blog_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PWD:senha_do_banco}

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurações de Mídia (multipart)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# os arquivos serão salvos no seguinte diretório:
api.file.upload.path=uploads

# JSON Web Token
api.security.jwt.secret=${JWT_ACCESS_SECRET:uma-chave-secreta-muito-segura-123}